name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "Project/wine-quality.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out repositori Anda di bawah $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Pengaturan Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Periksa Variabel Env
      - name: Check Env
        run: |
          echo $CSV_URL

      # Instal dependensi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Jalankan proyek mlflow
      - name: Run mlflow project
        run: |
          cd "Modul 2 - Membangun dan Mengelola Metadata dengan Tools Open-Source/Latihan Version Control/Project"
          mlflow run . --env-manager=local
